/*
Operadores Lógicos
&& -> AND -> E -> TODAS AS EXPRESSÕES PRECISAM SER VERDADEIRAS PARA RETORNAR TRUE
|| -> OR -> OU -> UMA DAS DUAS EXPRESSÕES PRECISA SER VERDADEIRA PARA RETORNAR TRUE
! -> -> NÃO -> NEGA A EXPRESSÃO
*/